### ISSUE TITLE
Run slowly and how to quit?

### ISSUE THREAD

**Issue by imistyrain** [OValery16/gender-age-classification#7]
I tried to let it run with a usb camera. But it runs slowly and when I want to quit, after pressed Ctrl+C, the screen freezes.

**Comment by OValery16** [comment]
do you run the prediction on the CPU or the GPU ?

**Comment by imistyrain** [comment]
GPU, with a 1080Ti.

**Comment by OValery16** [comment]
be careful when you process a video, you cannot process every single frame your camera is sending you. You have to skip some of them (prediction_age_gender.py line 47 skip =5)
